### ISSUE TITLE
Week 4: Assignment 1 - Project Proposal

### ISSUE THREAD

**Issue by YingCG** [ITwhitecliffe/software-project-May2024#1]

**Comment by YingCG** [comment]
**Task 1 & 2: Team organisation**
- [ ] Team contract
- [ ] Find a client
- [ ] Document the selected collaboration platforms and include links
- [ ] Provide your lecturer with access to the collaboration tools used for team discussions and planning
( Communication Platform, Team discussion, shared documentation, shared code, our agile Kanban board)


Task 3 & 4: Requirements analysis
- [ ] The problem overview
- [ ] Objectives: Clear and concise project goals.
- [ ] Stakeholders Requirements
- [ ] Schedule a meeting for requirement confirmation with client
- [ ] Follow up with confirmation of requirement with user stories


Task 5: Design Documentation
- [ ] Scope: A high-level view of what the project will achieve ( Website App, Management Software, Mobile App, or Game)
- [ ] Final design that addresses all client requirements
- [ ] Includes all wireframes and UI mockups
- [ ]  Highlight the key outcomes of the project.


Task 6: Project Plan (Prepare an Elevator pitch for your project )
- [ ] A brief description of how the project will be executed.
- [ ] Detailed breakdown of tasks and activities.
- [ ] Assignments: Specify who is responsible for each task.
- [ ] Timelines: A high-level timeline for project completion.
- [ ] Resources: Detail any tools, technologies, or platforms used.
- [ ] Monitoring and Reporting: Describe how progress will be tracked and reported.
- [ ] Risk Management: Identify potential risks and mitigation strategies.


Task 5 ,7 & 8: Client and lecturer meeting 
- [ ] Client meeting minutes recorded
- [ ] Client feedback considered and addressed
- [ ]  Present design document.


Task 9 & 10: Confirmation of the project proposal, and implementation plan
- [ ] Submit your project proposal


Task 11: Individual reflective journal 
- [ ] Reflection On your Active Experimentation as a developer
- [ ] Agile Ways Of Working, evaluating personal and my team's role
